# theme: jekyll-theme-slate

name: Piotr Tarasiewicz
title: null

# Your name to show in the footer
author: Piotr Tarasiewicz

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
#   - posts/*.md
